name: Run tests

on:
  push:
    branches: [ master, feature/*, bug/* ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 15.x

    - run: npm ci
    - run: npm test
